export {default as Home} from './home/Home'
export {default as Login} from './login/Login'
export {default as SignUp} from './signUp/SignUp'
export {default as ForgotPassword} from './forgotPassword/ForgotPassword'
export {default as ResetPassword} from './forgotPassword/ResetPassword'
export {default as QR_Code} from './qr_code/QR_Code'
export {default as HealthExercises} from './healthExercises/HealthExercise'
export {default as Profile} from './profile/Profile'
export {default as AboutPage} from './about/AboutPage'
export {default as Contact} from './contact/Contact'

